site_name: ""
site_description: My Professional Portoflio 
site_author: Salomon Marquez
strict: true

repo_name: sblaizerwize/My-Professional-Portfolio
repo_url: https://sblaizerwize.github.io/My-Professional-Portfolio/
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Bioinformatics:
      - bioinformatics/nextflow-for-rnaseq-aws.md
  - Machine Learning:
      - machine-learning/classification-splice-junction.ipynb
      - machine-learning/used-car-predictions-for-kagglex-competition.ipynb
  - Natural Language Processing: 
      - natural-language-processing/a-journey-through-text-data-competitions.ipynb
      - natural-language-processing/in-depth-analysis-of-kaggle-and-arxiv-datasets.ipynb
      - natural-language-processing/analyzing-movie-genre-predictions-using-transformers.ipynb
      - natural-language-processing/higher_order_huggingface_models_for_movie_predictions.ipynb
  - Technical Writing:
      - technical-writing/index.md

theme:
  name: "material"
  toc:
    max_level: 3  # Show H1, H2, H3, and H4 levels
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: black
      toggle:
        icon: material/brightness-auto
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: black
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: black
      toggle:
        icon: material/brightness-4
        name: "Switch to system preference"
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  language: en 

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sblaizerwize
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sblaizer/
    - icon: fontawesome/solid/paper-plane
      link: mailto:phd.smarquez@gmail.com

markdown_extensions:
- attr_list
- admonition
- pymdownx.details
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- def_list
- pymdownx.tasklist:
    custom_checkbox: true

plugins:
  - search
  - mkdocs-jupyter
  - include-markdown 

copyright: 2025 - Salomon Marquez
